#!/usr/bin/zsh
git clone https://github.com/dvallon906/ch.okapi.sync_manager.git
sudo launchctl unload /Library/LaunchDaemons/sync_manager_service.plist
sudo cp /opt/okapi/deamons/ch.okapi.sync_manager/services/sync_manager_service.plist /Library/LaunchDaemons/
sudo chmod +x /opt/okapi/deamons/ch.okapi.sync_manager/src/sync_manager.py
sudo launchctl start ch.okapi.sync_manager_service